version: "3.3"

services:
  mongodb:
    image: mongo:5.0.3
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb
